ysudo: required
dist: trusty
language: java
notifications:
  slack: cvtron:zpn5EYMgd1chDwtF1goXhpyb#bots
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
jdk:
  - oraclejdk8
node_js:
  - 9
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - nvm install node
  - npm install -g yarn
  - npm install -g coveralls
install:
  - yarn install
script:
  - yarn test